### ISSUE TITLE
Options validation for autoPad="explict" should be ignored in conv2d

### ISSUE THREAD

**Issue by Honry** [webmachinelearning/webnn-polyfill#146]
Following options validation at https://github.com/webmachinelearning/webnn-polyfill/blob/master/src/nn/ops/conv2d.ts#L43 should be ignored, since the `options.padding` has a default value `[0, 0, 0, 0]`.
```
    utils.assert(
        !(options.autoPad === MLAutoPad.explicit &&
          options.padding === undefined),
        'The padding parameter should be assigned when autoPad is explicit.');
```

**Comment by Honry** [comment]
@BruceDai, PTAL, thanks!

**Comment by Honry** [comment]
The spec doesn't specify that there should be an error thrown when the "options.padding" is `undefined` and the `autoPad` is 'explicit'. 

My understanding is, according to spec, when `autoPad` is `explicit`, the values of `options.paddings` should be used, i.e. if it's not presented, it will use `[0, 0, 0, 0]`.

**Comment by BruceDai** [comment]
> My understanding is, according to spec, when autoPad is explicit, the values of options.paddings should be used

Correct.

I added this check according to https://github.com/webmachinelearning/webnn-polyfill/pull/93#discussion_r672888590.

Does it need update spec by assigning `padding` with default `[0, 0, 0, 0]`, @huningxin？

```
dictionary MLConv2dOptions {
  sequence<long> padding = [0, 0, 0, 0];
  // others options... 
}
```

**Comment by huningxin** [comment]
> Does it need update spec by assigning `padding` with default `[0, 0, 0, 0]`, @huningxin？

spec does say that , please check https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-conv2d

> padding: a sequence of long of length 4. The additional rows and columns added to the beginning and ending of each spatial dimension of input, [beginning_height, ending_height, beginning_width, ending_width]. If not present, the values are assumed to be [0,0,0,0].
