### ISSUE TITLE
Style Transfer failed with WebGL backend

### ISSUE THREAD

**Issue by Honry** [webmachinelearning/webnn-polyfill#174]
Sample: https://webmachinelearning.github.io/webnn-samples/style_transfer/index.html

Wasm backend works, while WebGL backend throws error: `Binary was compiled with different shapes than the current args. Shapes 1,8,270,270 and 1,270,270,8 must match` from `convTranspose2d` op compilation.

**Comment by BruceDai** [comment]
Thanks @Honry, I will investigate and fix this issue.
