### ISSUE TITLE
Drop test directory from NPM package

### ISSUE THREAD

**Issue by dontcallmedom** [webmachinelearning/webnn-polyfill#196]
The NPM package ships with the 12 Mo test directory - it's not clear to me that it's needed in the package in the first place, so I would suggest removing "test" from the [directories in package.json](https://github.com/webmachinelearning/webnn-polyfill/blob/ef29803cf4bcf274d65b4f2a68447cdcd113c0a3/package.json#L8).

**Comment by BruceDai** [comment]
Thanks @dontcallmedom 
Agreed, the users would run these tests by downloading this repository if they had interests. Let's remove it.

**Comment by anssiko** [comment]
+1

@BruceDai please exclude the test dir from npm and ping @honry to publish a new package once done.

**Comment by BruceDai** [comment]
Fixed by #197. 

@dontcallmedom Please take a look https://cdn.jsdelivr.net/npm/@webmachinelearning/webnn-polyfill@0.1.3/ , thanks.

**Comment by BruceDai** [comment]
Closing it, thanks.
