### ISSUE TITLE
Archive this project

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-polyfill#239]
WebNN polyfill won't be used by frameworks because they have their own Wasm and WebGPU implementations.

/cc @BruceDai @ibelem @reillyeon

**Comment by anssiko** [comment]
@huningxin I will mark this repository as archived and read-only. (And we can unarchive if we need to do some tweaks still.)

This project was super helpful in demonstrating early feasibility of the WebNN API. Now that the [native implementations](https://webmachinelearning.github.io/webnn-status/) across multiple backends track the latest specification closely all web developers are advised to use the native implementations for their development and experimentation needs.

Thanks everyone for your contributions to this polyfill!
