### ISSUE TITLE
Fix CTS failures due to API change

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-polyfill#38]
There are 50 failures of [CTS](https://webmachinelearning.github.io/webnn-polyfill/test/cts.html) due to API change of #36 .

@BruceDai , please help fix them. Thanks!

**Comment by huningxin** [comment]
Thanks @BruceDai for taking this issue, looking forward to your code contribution.

@anssiko , I added Bruce as collaborator of this repo. So Bruce can be assigned.

**Comment by anssiko** [comment]
Thanks @BruceDai for your help. Keeping this polyfill up to date is important as it helps web developers experiment with the new API shape.

**Comment by BruceDai** [comment]
Thanks @anssiko and @huningxin. I've fixed it by #39, PTAL, thanks.
