### ISSUE TITLE
Add model test for MobileNetV2

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-polyfill#41]
MobileNetV2 is one of the [first-wave models](https://github.com/webmachinelearning/webnn/blob/master/op_compatibility/first_wave_models.md).

**Comment by BruceDai** [comment]
@huningxin I will take this task, thanks.

**Comment by BruceDai** [comment]
Link #49

**Comment by BruceDai** [comment]
PR #49 was merged, so close it.
