### ISSUE TITLE
[test] Failed to test mobilenetv2 batchnorm nchw with test_data_set_0.

### ISSUE THREAD

**Issue by BruceDai** [webmachinelearning/webnn-polyfill#55]
Base on [MobileNet v2-1.0 model and test data](https://s3.amazonaws.com/onnx-model-zoo/mobilenet/mobilenetv2-1.0/mobilenetv2-1.0.tar.gz) of [mobilenet/README.md](https://github.com/onnx/models/blob/8d50e3f598e6d5c67c7c7253e5a203a26e731a1b/vision/classification/mobilenet/README.md), we're adding mobilenetv2 batchnorm model tests of pr #49, with input and output data of test_data_set_0, we got this AssertionError error:
```
AssertionError: expected false to be true
    at Module.checkValue (utils.js:37:12)
```
, the delta of expected data of ouput[97]  **0.015684127807617188**, with actual data output[97] **0.015800103545188904** is 0.00011597573757171631, it isn't satisfied with the criteria by atol 1e-5 as and rtol as 1e-3.
```
delta <= atol + rtol * expected
```
For CI pass, I skipped to test mobilenetv2 batchnorm model tests with this test_data_set_0.

@huningxin Any suggestion, thanks.

**Comment by huningxin** [comment]
Given webnn-native is adding batchNorm and mobilenet support in PR https://github.com/webmachinelearning/webnn-native/pull/10, we probably can check the result of webnn-native result and compare it with the polyfill.

**Comment by BruceDai** [comment]
Thanks @huningxin .

Here're ouput[97] results of webnn-native on Windows platfrom by TGLi7-1165G7 Asus ZenBook Flip S laptop.
The data (0.015800103545188904) of webnn-polyfill is much closed to data (0.0157979) of webnn-native + DML backend. 

|expected|webnn-polyfill|webnn-native + OpenVINO backend (CPU)| webnn-native + DML backend (GPU)|
|----|----|----|----|
|0.015684127807617188|0.015800103545188904|0.0157056|0.0157979|


Note: Use OpenVINO version [2021.2](https://docs.openvinotoolkit.org/2021.2/openvino_docs_install_guides_installing_openvino_linux.html#install-openvino).

**Comment by BruceDai** [comment]
I checked the criteria of testing ONNX models on https://github.com/onnx/models/blob/master/workflow_scripts/ort_test_dir_utils.py#L238 to https://github.com/onnx/models/blob/master/workflow_scripts/ort_test_dir_utils.py#241, code are as following, it uses atol=1.e-3 and rtol=1.e-3 criteria.
```python
if expected.dtype.char in np.typecodes['AllFloat']:
  if not np.isclose(expected, actual, rtol=1.e-3, atol=1.e-3).all():
    print('Mismatch for {}:\nExpected:{}\nGot:{}'.format(output_names[idx], expected, actual))
    failed = True
```

When I tried above criteria (atol=1.e-3 and rtol=1.e-3), this mobilenetv2 batchnorm nchw with test_data_set_0 could pass.

@huningxin May we follow this criteria (atol=1.e-3 and rtol=1.e-3) to run those model tests from ONNX models? Any suggestion, thanks.

**Comment by huningxin** [comment]
@BruceDai , thanks for the investigation.

> May we follow this criteria (atol=1.e-3 and rtol=1.e-3) to run those model tests from ONNX models? Any suggestion, thanks.

Given the test data comes from ONNX, the webnn test should follow the its criteria setting.

**Comment by BruceDai** [comment]
Thanks @huningxin.
I will updated those model tests with that criteria setting.
