### ISSUE TITLE
Implement 'same-lower' autoPad option for conv2d op.

### ISSUE THREAD

**Issue by BruceDai** [webmachinelearning/webnn-polyfill#65]
There's implement on https://github.com/webmachinelearning/webnn-polyfill/blob/master/src/nn/ops/conv2d.ts#L136
```js
          // Calculate the explicit paddings for 'same-lower'
          if (this.autoPad_ === MLAutoPad['same-lower']) {
            padding = [[0, 0], [0, 0], [0, 0], [0, 0]];
            const outputSizes = [0, 0];
            for (let i = 0; i < 2; ++i) {
              outputSizes[i] = Math.ceil(input.shape[1 + i] / this.strides_[i]);
            }
            const totalPadding: [number, number] = [0, 0];
            for (let i = 0; i < 2; ++i) {
              totalPadding[i] = this.strides_[i] * (outputSizes[i] - 1) +
                  this.outputPadding_[i] +
                  ((filter.shape[i] - 1) * this.dilations_[i] + 1) -
                  input.shape[1 + i];
            }
            for (let i = 0; i < 2; ++i) {
              padding[i + 1][0] =
                  totalPadding[i] - Math.floor(totalPadding[i] / 2);
              padding[i + 1][1] = Math.floor(totalPadding[i] / 2);
            }
          }
```
while below two blocks don't implement to support 'same-lower':

https://github.com/webmachinelearning/webnn-polyfill/blob/master/src/nn/ops/conv2d.ts#L171
```js
          if (this.autoPad_ === MLAutoPad['same-upper']) {
            padding = 'same';
          } else {
            throw new Error(
                'tf.depthwiseConv2d only supports the same-upper auto pad.');
          }
```

https://github.com/webmachinelearning/webnn-polyfill/blob/master/src/nn/ops/conv2d.ts#L201
```js
        if (this.autoPad_ === MLAutoPad['same-upper']) {
          padding = 'same';
          this.outputSizes_ = [
            input.shape[1] * this.strides_[0],
            input.shape[2] * this.strides_[1],
          ];
        } else {
          throw new Error(
              'tf.conv2dTranspose only supports the same-upper auto pad.');
        }
```

I think these throw error blocks also need to implement 'same-lower' likes https://github.com/webmachinelearning/webnn-polyfill/blob/master/src/nn/ops/conv2d.ts#L136.

@huningxin What's your opinion, thanks

**Comment by huningxin** [comment]
I am not sure whether tf.depthwiseConv2d and tf.conv2dTranspose supports explicit paddings. If they support as tf.conv2d, please go head to implement them. Thanks.

**Comment by BruceDai** [comment]
Thanks @huningxin.
Now tf.depthwiseConv2d has supported explicit paddings, and tf.conv2dTranspose doesn't support explicit paddings.
I've submitted a PR of supporting tf.conv2dTranspose with explicit paddings https://github.com/tensorflow/tfjs/pull/5185.
