### ISSUE TITLE
Gemm only support 2D tensor

### ISSUE THREAD

**Issue by fujunwei** [webmachinelearning/webnn-polyfill#68]
The third optional operand must be [2D tensor](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-gemm).

Maybe we should remove `gemm scalar bias ` , `gemm single vector bias`  test case, and remove [0.0](https://github.com/webmachinelearning/webnn-polyfill/blob/master/test/ops/gemm.js#L435) for both `gemm aTranspose` and `gemm bTranspose`.

**Comment by huningxin** [comment]
@BruceDai , please help on this issue. Thanks!

**Comment by BruceDai** [comment]
@huningxin Please review pr #69, thanks.

**Comment by huningxin** [comment]
Opened webmachinelearning/webnn#171 for spec discussion.

**Comment by huningxin** [comment]
[gemm](https://webmachinelearning.github.io/webnn/#api-mlgraphbuilder-gemm) now supports scalar and broadcasting.
