### ISSUE TITLE
Enable the CI

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-polyfill#7]

**Comment by huningxin** [comment]
@BruceDai, could you please help on this issue? Thanks!

**Comment by BruceDai** [comment]
@huningxin That's OK, please assign it to me.

**Comment by huningxin** [comment]
Thanks in advance @BruceDai ! Hi @anssiko , could you please help add Bruce into the project? So we can assign issues to Bruce.

**Comment by anssiko** [comment]
@BruceDai can now be assigned to issues.
