### ISSUE TITLE
Tests don't work with wasm backend

### ISSUE THREAD

**Issue by huningxin** [webmachinelearning/webnn-polyfill#91]
Try https://webmachinelearning.github.io/webnn-polyfill/test/?backend=wasm

The error message in console is
```shell
worker.js onmessage() captured an uncaught exception: ReferenceError: o is not defined
```

@Honry , could you please take a look?

**Comment by Honry** [comment]
@huningxin, sure, I can reproduce this on latest Chrome Stable 91.0.4472.164, but not reproduce on latest Chrome Canary 94.0.4579.0, I will try with a simple test to see if this is upstream issue.

**Comment by Honry** [comment]
I found that build polyfill with `npm run build` will not reproduce this issue, while with `npm run build-production` reproduces. I will look into the webpack.

**Comment by Honry** [comment]
`build-production` will minimize the js code, and this is a known issue when pack wasm backend with minification. see https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/README.md#js-minification, I will add this workaround to fix the issue.
